name: mynews
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  bloc: ^9.2.0
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  google_fonts: ^8.0.2
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.11.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
    
  assets:
    - .env
    - assets/icons/
